### 1. Importing Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('heart_disease_data.csv')

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### 2. Data Preprocessing

In [5]:
df.shape

(303, 14)

In [6]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [8]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

### 3. Split into Feature and Target

In [9]:
X=df.drop(columns='target',axis=1)
Y=df['target']

### 4. Split into Train - Test data

In [10]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=2,stratify=Y,test_size=0.2)

### 5. Training Model

In [11]:
model=LogisticRegression()

In [12]:
model.fit(X_train,Y_train)

LogisticRegression()

### 6. Model Evaluation

In [13]:
X_train_prediction=model.predict(X_train)
accuracy_score(X_train_prediction,Y_train)

0.8512396694214877

In [14]:
X_test_prediction=model.predict(X_test)
accuracy_score(X_test_prediction,Y_test)

0.819672131147541

### 7. Prediction System

In [15]:
input=(58,1,0,114,318,0,2,140,0,4.4,0,3,1)
input_as_np_arr=np.asarray(input)
reshaped_input=input_as_np_arr.reshape(1,-1)
prediction=model.predict(reshaped_input)
if(prediction==1):
    print("Person has heart disease.")
else:
    print("Person does not have heart disease.")

Person does not have heart disease.


In [16]:
input_as_np_arr

array([ 58. ,   1. ,   0. , 114. , 318. ,   0. ,   2. , 140. ,   0. ,
         4.4,   0. ,   3. ,   1. ])

In [17]:
reshaped_input

array([[ 58. ,   1. ,   0. , 114. , 318. ,   0. ,   2. , 140. ,   0. ,
          4.4,   0. ,   3. ,   1. ]])

In [18]:
scaler=StandardScaler()
scaler.fit(X)
standard_input=scaler.transform(reshaped_input)

In [19]:
standard_input

array([[ 0.40075247,  0.68100522, -0.93851463, -1.00654424,  1.38633229,
        -0.41763453,  2.80375634, -0.42186226, -0.69663055,  2.89899873,
        -2.27457861,  2.22410436, -2.14887271]])

## Saving trained model

In [20]:
import pickle

In [21]:
filename='trained_heat_disease_model.sav'
pickle.dump(model,open(filename,'wb'))